version: '3'

services:
  api: 
      container_name: backendapi
      restart: always
      build: .
      ports:
          - "3001:3000"
        
  db:
      container_name: mysqldb
      image: mysql
      volumes:
          - ./sql-data/db:/var/lib/mysql
      ports: 
          - "3307:3306"
      env_file:
          - ./api/.env
