 # Utilizar la imagen oficial de Node.js como base
FROM node:18-alpine

# Establecer el directorio de trabajo en /app
#WORKDIR /app
RUN mkdir -p /usr/src/ionic-app

WORKDIR /usr/src/ionic-app

# Copiar los archivos de tu proyecto al contenedor
#COPY . .
COPY frontend/ARAN ./

# Instalar la CLI de Ionic
RUN npm install -g @ionic/cli

# Instalar las dependencias de la aplicación
RUN npm install

# Compilar la aplicación
RUN ionic build --prod

# Exponer el puerto 80 para que pueda ser utilizado por Nginx
EXPOSE 80

# Ejecutar el comando para iniciar la aplicación
CMD ["npm", "start"]