FROM node:18

# ENV NODE_ENV=development#production

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY api-whatsapp-ts/package*.json ./

RUN npm install

# copiar directorio actual dentro de contenedor actual
COPY . .

# Puerto para app messenger
EXPOSE 3003

VOLUME [ "/api-whatsapp-ts/node_modules" ]

CMD [ "npm", "run", "dev" ]