 # Utilizar la imagen oficial de Node.js como base
FROM node:18-alpine AS builder

# Establecer el directorio de trabajo en /app
#WORKDIR /app
RUN mkdir -p /usr/src/ionic-app

WORKDIR /usr/src/ionic-app

# Copiar los archivos de tu proyecto al contenedor
#COPY . .
COPY frontend/ARAN ./

# Instalar la CLI de Ionic
RUN npm install -g @ionic/cli

# Instalar las dependencias de la aplicación
RUN npm install

# Compilar la aplicación
RUN ionic build --prod

##
# Luego, empaquetar la aplicación en una imagen de Nginx
FROM nginx:1.23.4-alpine

# Eliminar el archivo de configuración por defecto de Nginx
RUN rm -rf /etc/nginx/conf.d/default.conf

# Copiar la configuración de Nginx personalizada
COPY nginx.conf /etc/nginx/conf.d/

# Copiar la aplicación construida desde la imagen de Node.js
COPY --from=builder /usr/src/ionic-app/www /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
##

# Exponer el puerto 80 para que pueda ser utilizado por Nginx
#EXPOSE 80

# Ejecutar el comando para iniciar la aplicación
#CMD ["npm", "start"]